name: Issue Mover
on:
  pull_request:
    types: ["ready_for_review", "converted_to_draft"]

jobs:
  issues:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: debug1
        run: echo "itten foo"
      - name: debug2
        run: echo "na ${{ github.event. }} na"
        run: echo "na ${{ github.event.pull_trequest }} na"
        run: echo "na ${{ github.event.pull_trequest.body }} na"

