name: Issue Mover
on:
  pull_request:
    types: ["ready_for_review", "converted_to_draft"]

jobs:
  issues:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: debug1
        run: echo "itten foo"
      - name: debug2
        run: echo ${{github.event}}

