name: Issue Mover
on:
  pull_request:
    types: ["ready_for_review", "converted_to_draft"]

jobs:
  issues:
    runs-on: ["ubuntu-latest"]
    env:
      PROJECT_ID: 13012631
      COLUMN_ID_OF_IN_PROGRESS: 15408994
      COLUMN_ID_OF_REVIEW: 15408997
      ISSUE_NUMBER: 11
    defaults:
      run:
        shell: bash
    steps:
      - name: debug1
        run: |
          echo "na ${{ github.event }} na"
          echo "na ${{ github.event.pull_request }} na"
          echo "na ${{ github.event.pull_request.body }} na"
          echo "EN" ${{ github.event_name }} "EN"
          echo "ET" ${{ github.event.type }} "ET"
      - name: debug2a - get list of projects
        run: |
              curl \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/projects
      - name: debug2b - get PR
        run: |
              curl \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/pulls/${{ github.event.number }}
      - name: debug2c - get columns of project
        run: |
              curl \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/projects/$PROJECT_ID/columns
      - name: debug2d1 - get cards in one column
        run: |
              curl \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/projects/columns/$COLUMN_ID_OF_IN_PROGRESS/cards
      - name: debug2d2 - get cards in other column
        run: |
              curl \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/projects/columns/$COLUMN_ID_OF_REVIEW/cards
      - name: debug2e 
        run: |
              curl \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER
      - name: debug2f - move card
        run: |
              curl \
                  -X POST \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/projects/columns/cards/66220864/moves \
                  -d '{"position":"bottom", "column_id": 15408994}';
      - name: debug3
        # grab the first line that starts with "Fixes", collect the ticket numbers from the line and move those tickets into their column.
        run: |
          for issueNumber in `echo "${{ github.event.pull_request.body }}" | grep -E "^Fixes" | head -n 1 | tr -d -C "0123456789#" | tr "#" "\n" | grep -E "[0-9]" | tr "\n" " "`; do
              echo "issueNumber:" $issueNumber;
              curlxxxxx \
                  -X POST \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/projects/columns/cards/$issueNumber/moves
                  -d '{"position":"bottom", "column_id": 15408997}';
          done;
          echo "last issueNumber:" $issueNumber;

