name: Issue Mover
on:
  pull_request:
    types: ["ready_for_review", "converted_to_draft"]

jobs:
  issues:
    runs-on: ["ubuntu-latest"]
    defaults:
      run:
        shell: bash
    steps:
      - name: debug2
        run: |
          echo "na ${{ github.event }} na"
          echo "na ${{ github.event.pull_request }} na"
          echo "na ${{ github.event.pull_request.body }} na"
      - name: debug3
        run: |
          for issueNumber in `echo "${{ github.event.pull_request.body }}" | grep -E "^Fixes" | head -n 1 | tr -d -C "0123456789#" | tr "#" "\n" | grep -E "[0-9]" | tr "\n" " "`; do
              echo "issueNumber:" $issueNumber;
          done;

