name: Issue Mover
on:
  pull_request:
    types: ["ready_for_review", "converted_to_draft"]

jobs:
  issues:
    runs-on: ["ubuntu-latest"]
    env:
      PROJECT_NAME: "trial-action"
      COLUMN_NAME_OF_DRAFT_PRS: "egyik"
      COLUMN_NAME_OF_NON_DRAFT_PRS: "masik"
    defaults:
      run:
        shell: bash
    steps:
      - name: "Move"
        run: |
              # figure out the GitHub ProjectID
              export projectID=$(curl -s \
                  -H "Accept: application/vnd.github.inertia-preview+json" \
                  -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/projects | jq '.[] | select(.name == "'$PROJECT_NAME'") | .id')
              echo "GitHub ProjectID for project \"$PROJECT_NAME\": "$projectID
              
              if [[ -z $cardNumber ]]; then
                  echo "The PR body has no card mnetioned in its Fixes: line, so no card has been moved."              
              fi

